version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .
            pip install pytest pytest-cov
      - run:
          name: lint & test
          command: |
            . venv/bin/activate
            # flake8 --exclude=venv* --statistics
            pytest -v --cov=resilience tests
